const events = [
  {
    title: 'Monthly Catch Up',
    desc: 'Team sync and KPIs overview.',
    time: '8:30 - 9:30',
    date: '2025-04-02',
    location: 'Rue Paul Dautier, Vélizy-Villacoublay, 78140, France',
    owner: 'Jacob Smith',
    invitees: [
      { name: 'Jacob Smith', email: 'jacob@example.com', photo: 'https://i.pravatar.cc/150?img=3' },
      { name: 'Sophie Turner', email: 'sophie@example.com', photo: 'https://i.pravatar.cc/150?img=5' }
    ],
    notificationMethod: 'Email',
    notificationTime: 30,
    notificationUnit: 'Minutes',
    color: 'red',
  },
  {
    title: 'Presentation',
    desc: 'Client delivery presentation.',
    time: '10:30 - 12:30',
    date: '2025-04-02',
    location: 'Avenue de Paris, Versailles, 78000, France',
    owner: 'Anna Lee',
    invitees: [
      { name: 'Anna Lee', email: 'anna@example.com', photo: 'https://i.pravatar.cc/150?img=4' }
    ],
    notificationMethod: 'SMS',
    notificationTime: 1,
    notificationUnit: 'Hours',
    color: 'orange',
  },
  {
    title: 'Code Review',
    desc: 'Review sprint PRs.',
    time: '15:00 - 16:00',
    date: '2025-04-03',
    location: 'Rue de Rennes, Paris, 75006, France',
    owner: 'Michael Scott',
    invitees: [],
    notificationMethod: 'Email',
    notificationTime: 15,
    notificationUnit: 'Minutes',
    color: 'blue',
  },
  {
    title: 'Reunion',
    desc: 'Quarterly strategy meeting.',
    time: '10:15 - 13:00',
    date: '2025-04-07',
    location: 'Place d’Italie, Paris, 75013, France',
    owner: 'David Lopez',
    invitees: [],
    notificationMethod: 'Email',
    notificationTime: 1,
    notificationUnit: 'Days',
    color: 'blue',
  },
  {
    title: 'Flight',
    desc: 'Flight to NYC for business trip.',
    time: '18:00 - 20:20',
    date: '2025-04-18',
    location: 'Aéroport Charles de Gaulle, Roissy-en-France, France',
    owner: 'Lina Brown',
    invitees: [],
    notificationMethod: 'Email',
    notificationTime: 2,
    notificationUnit: 'Hours',
    color: 'blue',
  },
  {
    title: 'Musical Event',
    desc: 'Live jazz at Philharmonie.',
    time: '20:15 - 22:30',
    date: '2025-04-12',
    location: 'Philharmonie de Paris, Paris, France',
    owner: 'Lucas Henry',
    invitees: [],
    notificationMethod: 'SMS',
    notificationTime: 1,
    notificationUnit: 'Hours',
    color: 'blue',
  },
  {
    title: 'Date',
    desc: 'Dinner reservation at fancy place.',
    time: '21:00 - 23:00',
    date: '2025-04-22',
    location: 'Le Meurice, Paris, France',
    owner: 'Emily Clark',
    invitees: [],
    notificationMethod: 'Email',
    notificationTime: 2,
    notificationUnit: 'Hours',
    color: 'blue',
  },
  {
    title: 'Exam',
    desc: 'Final exam in data structures.',
    time: '12:00 - 14:00',
    date: '2025-05-02',
    location: 'Université de Versailles, 78000, France',
    owner: 'Student',
    invitees: [],
    notificationMethod: 'Email',
    notificationTime: 1,
    notificationUnit: 'Days',
    color: 'blue',
  },
];

export default events;
